### ISSUE TITLE
UUIDs for all publicly visible IDs

### ISSUE THREAD

**Issue by AndriusA** [Hub-of-all-Things/HAT2.0#1]
For consideration: to avoid simple sequencing issues and further minimise exposure of internal HAT state, all publicly visible (via APIs) and hence database IDs should be converted to UUID type instead of auto-incrementing integers

**Comment by thiloplanz** [comment]
Hmm. That would be an incompatible change in the public API. Please either do this very soon or else wait until a "v2" of the protocol is required for other reasons.

**Comment by AndriusA** [comment]
obsoleted by APIv2
