### ISSUE TITLE
UserPassHandler should accept Basic-Auth in addition to query parameters

### ISSUE THREAD

**Issue by thiloplanz** [Hub-of-all-Things/HAT2.0#15]
As part of the URL, query parameters are often logged along the way, putting a password in there seems risky.

Please also allow sending the credentials via the Basic-Auth mechanism in the request header.

**Comment by AndriusA** [comment]
Yes, that is a temporary solution until we move for a better solution in
the next releade.

Pull requests are very welcome however

**Comment by thiloplanz** [comment]
Re: pull request.

That seems to conflict with your project license (No-Derivatives). Is it possible to change to something more "fork-friendly" like the Apache or even a GNU license?

**Comment by coolseraph** [comment]
Thanks a lot for the feed back. it will be changed to a more common based license once we have gone through our Beta stage. As we are still in alpha, we'd rather keep the public facing version under control for the time being. This only means that all changes will be formally made by the project team, and please do propose ideas and changes as your wish, and we really appreciate that! and we welcome all to contribute to the project. we have a tech forum to discuss such matter, if you'd like to join us ;) http://forum.hatdex.org/

**Comment by thiloplanz** [comment]
Glad to hear that you are considering a more liberal license. That would make contributions (and frankly, adoption as well) easier.

In that spirit, please pick one of the "normal ones".


> Can I apply a Creative Commons license to software?

> We recommend against using Creative Commons licenses for software. Instead, we strongly encourage you to use one of the very good software licenses which are already available. We recommend considering licenses made available by the Free Software Foundation or listed as “open source” by the Open Source Initiative.

> Unlike software-specific licenses, CC licenses do not contain specific terms about the distribution of source code, which is often important to ensuring the free reuse and modifiability of software. Many software licenses also address patent rights, which are important to software but may not be applicable to other copyrightable works. Additionally, our licenses are currently not compatible with the major software licenses, so it would be difficult to integrate CC-licensed work with other free software. Existing software licenses were designed specifically for use with software and offer a similar set of rights to the Creative Commons licenses.

**Comment by AndriusA** [comment]
Licensing solved separately. Authentication code will be merged into master with the next merge.
