### ISSUE TITLE
API requires field/table name in addition to field/table id, but does not validate it

### ISSUE THREAD

**Issue by thiloplanz** [Hub-of-all-Things/HAT2.0#19]
When doing things like creating a new record with fields filled in you need to provide the API with the relevant field or table name in addition to the field or table id (which is already unique). If the name is missing the API call is rejected.

But it seems that the names provided do not have to be correct (i.e. match the field/table definition). You can post any dummy name, and the request will be processed.

If the purpose of including the name in the request is to provide for extra validation of intent / avoid mistakes, then this parameter should be checked and the request refused when invalid names are specified.

If there is no validation, there should be no need to pass in the name at all (which makes writing API client code easier, too).

Possible middle-ground / best-of-both-worlds: Make the name optional, but if specified, it must be correct.

**Comment by thiloplanz** [comment]
This issue is even more pronounced when attaching properties to entities. Only the propertyId seems to be used really, but the API requires to also specify details about property type and unit of measurement in nested objects.

**Comment by AndriusA** [comment]
obsoleted by APIv2
