### ISSUE TITLE
Reducing the number of entity tables

### ISSUE THREAD

**Issue by AndriusA** [Hub-of-all-Things/HAT2.0#2]
To simplify the underlying data model (not the conceptual one), consider merging all entity data tables (person, thing, event, location and organisation) into one, differentiated by `kind`, simplifying api programming and reducing the number of tables

**Comment by coolseraph** [comment]
in HAT model, we don't expect `Person` , to grow too much, but `thing`,  `event`, and `location` to grow quite a lot. Will put all in the same table give us problems with traversaling that table? index on `kind` will help, but not sure about a very long table of `things`. views?

**Comment by AndriusA** [comment]
achieved by APIv2
