### ISSUE TITLE
Some API calls return 401 (Unauthorized) instead of 400 (Bad Request) for invalid input

### ISSUE THREAD

**Issue by thiloplanz** [Hub-of-all-Things/HAT2.0#21]
When calling into the API to create a new table (`POST /data/table`) with invalid data (such as an empty JSON object `{}`) you correctly get error code 400 (Bad Request "Object is missing required member 'name'" ) when you are authenticating with username and password, but when authenticating with an acccess token you get 401 (Unauthorized), even though the token is valid. 

The correct error code (and the very useful detailed JSON validation or database error message that goes along with it) should be returned when a valid access token is presented as well.

**Comment by AndriusA** [comment]
fixed earlier migration to Play framework
