### ISSUE TITLE
Deployment documentation out of date?

### ISSUE THREAD

**Issue by TheAncientGoat** [Hub-of-all-Things/HAT2.0#26]
Running the deploy.sh script throws a couple of missing file errors  -

```
Setting up database user and database
dbuser: hat20test, database: hat20test
CREATE ROLE hat20test NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT LOGIN;
createuser: creation of new role failed: ERROR:  role "hat20test" already exists
createdb: database creation failed: ERROR:  database "hat20test" already exists
ALTER ROLE
Handling schemas
NOTICE:  drop cascades to 2 other objects
DETAIL:  drop cascades to extension uuid-ossp
drop cascades to extension pgcrypto
DROP SCHEMA
CREATE SCHEMA
ALTER SCHEMA
Setting up database
CREATE EXTENSION
CREATE EXTENSION
./deployment/deploy.sh: line 31: ./src/sql/HAT-V2.0.sql: No such file or directory
./src/sql/HAT-V2.0.sql
Setting up corresponding configuration
Setting up HAT access
./deployment/deploy.sh: line 51: ./src/sql/boilerplate/authentication.sql: No such file or directory
bash: applyEvolutions.sh: No such file or directory
Preparing the project to be executed
```

It seems like references to code that's present in https://github.com/Hub-of-all-Things/hat-database-schema - but this isn't a submodule of the HAT2.0 repo, and even then, the HAT-V2.0.sql file doesn't seem to be present in any repo?

**Comment by AndriusA** [comment]
Thanks @TheAncientGoat,

It is I'm afraid out of date indeed. Will try to get it fixed by mid next week.

I'm not sure however why you don't see hat-database-schema as a submodule? I've just done a fresh clone:

```
$ git clone https://github.com/Hub-of-all-Things/HAT2.0
Cloning into 'HAT2.0'...
remote: Counting objects: 6260, done.
remote: Total 6260 (delta 0), reused 0 (delta 0), pack-reused 6260
Receiving objects: 100% (6260/6260), 2.92 MiB | 2.27 MiB/s, done.
Resolving deltas: 100% (3190/3190), done.
Checking connectivity... done.
$ cd HAT2.0/
$ git submodule status
-f23e9e26dfdf05ecc70138f8b6a9c35b16daa226 hat-database-schema
$ git submodule init
Submodule 'hat-database-schema' (https://github.com/Hub-of-all-Things/hat-database-schema.git) registered for path 'hat-database-schema'
$ git submodule update
Cloning into 'hat-database-schema'...
remote: Counting objects: 73, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 73 (delta 0), reused 0 (delta 0), pack-reused 70
Unpacking objects: 100% (73/73), done.
Checking connectivity... done.
Submodule path 'hat-database-schema': checked out 'f23e9e26dfdf05ecc70138f8b6a9c35b16daa226'
```

Since we have moved away to Kubernetes-based deployments the vanilla bash script based ones are a bit behind. If you want to try and run the HAT locally before we update the scripts, take a look at the [.travis.yml](../blob/master/.travis.yml):

- `before_script` part initialises the database
- `script` part does the building and testing in this case. If you replace the last line that runs the tests with `sbt run` it will run the server locally on the default port 9000

**Comment by TheAncientGoat** [comment]
Managed to get it running thanks - clean clone resolved the submodule issue, and the travis steps are pretty clear.

Would it help if I update the readme? Or are there other considerations/steps that I might have missed?

**Comment by AndriusA** [comment]
I believe the reworked setup has now simplified local deployment and it is currently easy to follow the steps and have the project running locally
