### ISSUE TITLE
Trying to run the project, getting an error

### ISSUE THREAD

**Issue by TorontoBoy** [Hub-of-all-Things/HAT2.0#36]
I am following the install instructions from: https://github.com/Hub-of-all-Things/HAT2.0 specifically Running the project, HAT Setup.

Cloned the repository:
https://github.com/Hub-of-all-Things/HAT2.0
Steps 1-3, creating the postgreSQL db, compiling the project and local domain mapping went without error.

Step 4 sbt "project hat" -Dconfig.resource=dev.conf run give me this error:

```
don-u@don--u:~$ sbt compile

[info] Loading project definition from /home/don-w510-u/project
[info] Set current project to don-u (in build file:/home/don-u/)
[info] Executing in batch mode. For better performance use sbt's shell
[success] Total time: 0 s, completed 13-Nov-2017 8:28:01 AM

don-u@don-u:~$ sbt "project hat" -Dconfig.resource=dev.conf run

[info] Loading project definition from /home/don-u/project
[info] Set current project to don-w510-u (in build file:/home/don-u/)
[error] Not a valid project ID: hat
[error] project hat
[error]            ^
```
Also tried:
```
don-u@don-u:~$ sbt "project hat2.0" -Dconfig.resource=dev.conf run
[info] Loading project definition from /home/don-u/project
[info] Set current project to don-u (in build file:/home/don-u/)
[error] Expected project ID
[error] project hat2.0
[error]             ^
```
Please tell me what I am doing incorrectly. Thanks, Don

**Comment by AndriusA** [comment]
you do not seem to be in the project directory? As per:
```
[info] Loading project definition from /home/don-w510-u/project
```

sbt commands need to be run from inside the project directory - it is basically an equivalent to "make" for Scala projects.

**Comment by TorontoBoy** [comment]
Thanks AndriusA, cd to the project directory was the key. That first download and install took a very long time, but eventually it did come back to life.

I have the front "You've Landed on a HAT page!" Hurray!

**Comment by AndriusA** [comment]
Great!

Indeed, the first build with Scala always takes a while - even if the final package is fairly small, downloading all dependencies takes a while and Scala's compilation time is infamously long

Closing this now

**Comment by TorontoBoy** [comment]
Hi AndriusA. I think the startup page I am receiving is an error page "Hat not available". The two buttons on the page link off to https://hubofallthings.com/main/what-is-the-hat/ (file not found) and https://hatters.hubofallthings.com/ .

Is this an actual error page or the default front page? How can I create a hat? For sure I am missing something.
