### ISSUE TITLE
From Install instructions, getting "Hat not available" startup screen. Is this normal?

### ISSUE THREAD

**Issue by TorontoBoy** [Hub-of-all-Things/HAT2.0#37]
Continued from "Trying to run the project, getting an error " https://github.com/Hub-of-all-Things/HAT2.0/issues/36 

Hi AndriusA. I think the startup page I am receiving is an error page "Hat not available". The two buttons on the page link off to https://hubofallthings.com/main/what-is-the-hat/ (file not found) and https://hatters.hubofallthings.com/ , and do not allow me to create a hat on my local system.

Is this an actual error page or the default front page? Looking at the page source I see html  such as 
```
<div class="error-logo">, <h1 class="error-title">, <h3 class="error-subtitle">, <h3 class="error-subtitle-action">
```

I am getting some warnings that I don't know how to resolve, about private keys.

How can I create a hat? For sure I am missing something. 

```
[info] Exporting web-assets:hat
[info] Compiling 16 Scala sources and 3 Java sources to /home/don-w510-u/HAT2.0/hat/target/scala-2.11/classes...
[WARN ] [11/13/2017 09:09:01] [o.h.h.r.a.HatServerActor] Error while trying to fetch HAT bobtheplumber.hat.org:9000 Server configuration: Private Key for bobtheplumber.hat.org:9000 not found
[WARN ] [11/13/2017 09:09:01] [o.h.h.r.HatServerProviderImpl] Error while retrieving HAT Server info: Private Key for bobtheplumber.hat.org:9000 not found
```
Thanks, Don

**Comment by AndriusA** [comment]
How exactly do you run the project?

It doesn't look like the dev environment configuration gets picked up as instructed by the command:
```
sbt "project hat" -Dconfig.resource=dev.conf run
```

You could try surrounding the config parameter with quotes as well:
```
sbt "project hat" "run -Dconfig.resource=dev.conf"
```

In any case, the logs are not complete enough to be able to tell, post the from the start? A successful dev environment start begins with:
```
--- (Running the application, auto-reloading is enabled) ---

[info] p.c.s.AkkaHttpServer - Listening for HTTP on /0:0:0:0:0:0:0:0:9000

(Server started, use Enter to stop and go back to the console...)

Adding specs2!
Adding specs2!
[INFO ] [11/23/2017 08:46:37] [o.h.h.m.DevHatInitializer] Initializing HATs: Map(bobtheplumber -> DevHatConfig(bobtheplumber,Bob the Plumber,$2a$10$ogx5pbbGn604l1ljpdhgo.pA1svWkaNLDJsMWp8WxvTyVS6lWnTaS,hpp,HAT Platform Provider,$2a$10$ogx5pbbGn604l1ljpdhgo.pA1svWkaNLDJsMWp8WxvTyVS6lWnTaS,Config(SimpleConfigObject({"dataSourceClass":"org.postgresql.ds.PGSimpleDataSource","numThreads":3,"properties":{"databaseName":"testhatdb1","password":"testing","user":"testhatdb1"}}))))
```
