### ISSUE TITLE
Add API support for list values

### ISSUE THREAD

**Issue by augustinas** [Hub-of-all-Things/HAT2.0#5]
As an example, user might want to save their FB post record with one of the values being a list of likes. Currently storing such a record is cumbersome. It requires the creation of additional "likes" data source model and manually referencing each "like" record inside the "post" record.

**Comment by thiloplanz** [comment]
I think fields are inherently multi-valued: You can add more than one value for the same field for a given record. Does that help? (Probably only works well for single-field/single-String values, not for groups of related fields)

**Comment by AndriusA** [comment]
obsoleted (and achieved) by APIv2
