### ISSUE TITLE
location relationship with (event,thing,organisation) cannot be Created

### ISSUE THREAD

**Issue by RGlotnis** [Hub-of-all-Things/HAT2.0#6]
Having created the location and (event,thing,organisation):
location
```
{
  "id": 191,
  "name": "stairs"
}
```
thing
```
{
  "id": 44,
  "name": "pressure sensor"
}
```
I cannot create a relationship between them by posting
```
{
 "relationshipType": "parent child"
}
```
to 
`location/191/thing/44?userAuth..`

Returns 400 and seems like it tries to bind the first id to the thing rather than taking the second one as designed:
```
ERROR: insert or update on table "locations_locationthingcrossref" violates foreign key constraint "thing_id_refs_id_fk"
  Detail: Key (thing_id)=(191) is not present in table "things_thing".
```

**Comment by AndriusA** [comment]
Should be fixed in property_management branch, commit 3c42fc4f049fc6a052597b687165975052c12ac1 with a lot of other bugs, please merge that branch into testing
